<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <AssemblyName>AbyssalEcologies</AssemblyName>
    <RootNamespace>AbyssalEcologies.Plugin</RootNamespace>
    <Version>0.3.0</Version>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RestoreAdditionalProjectSources>https://api.nuget.org/v3/index.json;https://nuget.bepinex.dev/v3/index.json</RestoreAdditionalProjectSources>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../AbyssalEcologies.Core/AbyssalEcologies.Core.csproj" />
    <PackageReference Include="BepInEx.Analyzers" Version="1.*" PrivateAssets="all" />
    <PackageReference Include="BepInEx.Core" Version="5.4.21" />
    <PackageReference Include="UnityEngine.Modules" Version="2019.4.36" IncludeAssets="compile" />
    <PackageReference Include="Subnautica.GameLibs" Version="82304.0.0-r.0" />
    <PackageReference Include="PolySharp" Version="1.16.0" PrivateAssets="all" />
    <PackageReference Include="Subnautica.Nautilus" Version="1.0.0-pre.53" PrivateAssets="all" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
  </ItemGroup>
</Project>
